### ISSUE TITLE
Worqor Zormor b2 revival glitch-bricking

### ISSUE THREAD

**Issue by ayo-bruh** [ffxivcode/AutoDuty#306] opened 2024-08-29 18:01 UTC
Dying at B2 now frequently bricks runs as it will not use revival shortcut at entrance. stops for bit, then seemingly tries to use or something - 'cannot execute' red message comes up. then just runs down path to B1 and gets stuck at (11.6, 14.8) each time. does this consistently now, even after exiting dungeon and starting fresh run. (previously was not doing this at all hardly, despite B2 frequently causing wipes since NPCs adjust late with spreads+vuln from crystal ground aoe)

path is on "Revival+-53.32, 321.29, -32.54|" step when getting stuck occurs

nothing in xxlog relating to this. does not appear to be vnav as happens consistently enough and after fresh game reboot etc. DPS class, non-w2w path. v136

**Comment by Herculezz55** [comment] 2024-09-01 05:42
closing for now as couldnt reproduce

**Closed by Herculezz55** 2024-09-01 05:42 UTC
